name: Evaluation and deployment
on: [workflow_dispatch]
jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: download models
        uses: dawidd6/action-download-artifact@v2
        with:
            workflow: train.yml
            name: models
            path: data/models/
      - name: download features
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: extract_features.yml
          name: features
          path: data/features/
      - name: install requirements
        run: pip install -r deps/preprocessing.txt
      - name: run eval
        env:
          TEST_DATA: "data/features/train.csv"
          MODELS: "data/models"
          OPTMAL_MODEL: "data/models/best_model.pkl"
        run: python src/eval.py
      - name: save to storage
        uses: actions/upload-artifact@v3
        with:
          name: models
          path: data/models

  deploy:
    runs-on: self-hosted
    needs: eval
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: download models
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: train.yml
          name: models
          path: data/models/
      - name: download labeler
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: extract_features.yml
          name: labeler
          path: data/label_encoder.pkl
      - name: install requirements
        run: pip install -r deps/prod.txt
      - name: start app
        run: python3.11 api/api.py

