name: Extract features from fetched dataset
on: [workflow_dispatch]
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: download
        uses: dawidd6/action-download-artifact@v2
        with:
            workflow: fetch.yml
            name: data-storage
            path: data/data-storage/
      - name: prep dir
        run: mkdir data/models && mkdir data/features
      - name: install requirements
        run: pip install -r deps/preprocessing.txt
      - name: run script
        env:
          DATA: "data/data-storage/results.csv"
          TRAIN_DATA: "data/features/train.csv"
          TEST_DATA: "data/features/test.csv"
          LABELER: "data/models/label_encoder.pkl"
        run: python src/label_data.py
      - name: upload features
        uses: actions/upload-artifact@v3
        with:
          name: data-storage
          path: data/features/
      - name: upload model
        uses: actions/upload-artifact@v3
        with:
          name: data-storage
          path: data/models/
